theme: jekyll-theme-cayman
title: Ariel Szabo
description: I am a self taught programmer interested in developing and applying machine and deep learning methods to problems, <br/> while gathering data driven insights and conclusions.
github:
   is_project_page: false
